---
- name: Install Nginx on Worker Nodes
  hosts: all
  become: true
  tasks:
    - name: Install Nginx on Worker Nodes
      docker_swarm_service:
        name: install nginx
        image: nginx
        placement:
          constraints:
            - node.role == worker
        publish:
        - published_port: "8888"
          target_port: 80
          protocol: tcp
          mode: host
