---
- name: Install Nginx on Worker Nodes
  hosts: worker
  become: true
  tasks:
    - name: Install Nginx on Worker Nodes
      docker_swarm_service:
        name: nginx_service
        image: nginx
        placement:
          constraints:
            - node.role == worker
